idlergear_version = "0.7.33"

[project]
name = ""

[github]

[daemon]
auto_start = true

[backends]
task = "local"
explore = "local"
note = "local"
plan = "local"
reference = "local"

[watch]
enabled = "true"
debounce = "5"
files_changed_threshold = "5"
uncommitted_lines_threshold = "100"
test_failures_threshold = "1"
detect_todos = "true"
detect_fixmes = "true"
detect_hacks = "true"
poll_interval = "10"

[test]
block_on_failure = false
stale_threshold_seconds = 7200

[graph]
auto_update = true

[wiki]
enabled = "true"
